name = "Komi-Zyrian"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Komi-Zyrian spellchecker"
kpv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Komi-Zyrian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
kpv = "TRANSLATE: A spellchecker for Komi-Zyrian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.kpv"

[windows]
system_product_code = "{66DB3E61-787C-470B-967D-99EF04C9F451}_is1"
legacy_product_codes = [
    { value = "5081736D-0973-4825-958B-A41C9ECAFD3C", kind = "nsis" },
    { value = "57203AE7-3923-4958-A89D-906C82C81B9A", kind = "nsis" }
]
