template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "a03015fd00a15a0ad51da907dc4891c29ab9c8b2"

[replacements]
__GLOTTOLOG_ID__ = "komi1268"
__REPO__ = "lang-kpv"
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
