template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "komi1268"
__REPO__ = "lang-kpv"
__UND2C__ = "kpv"
__UNDEFINED__ = "Komi-Zyrian"
__UND__ = "kpv"
