# Grammar tags for the Komi analyser

Here is an alphabetical list of the morphological tags
used in [the Komi analyser](http://giellatekno.uit.no/cgi/index.kom.eng.html).

[Здесь вы можете увидеть, что грамматические метки означают на русском языке](docu-grammartags.rus.html)

* **+A** = adjective
* **+ABBR** = abbreviation
* **+ACR** = acronym
* **+AN** = participle AN
* **+ANA** = participle ANA
* **+ANAA** = participle ANAA
* **+Abe** = abessive
* **+Abl** = ablative
* **+Acc** = accusative
* **+Adv** = adverb
* **+Apr** = approximative
* **+CC** = conjunction
* **+CHOZH** = gerund CHOZH
* **+CLB** = clause boundary
* **+CS** = subjunction
* **+Car** = caritive
* **+Card** = cardinal
* **+Clt** = clitic
* **+Cns** = consecutive
* **+Coll** = collect
* **+Com** = comitative
* **+Comp** = comparative
* **+ConNeg** = conneted negative form
* **+Cond** = conditional
* **+Dat** = dative
* **+Det** = determinative
* **+Egr** = egressive
* **+Ela** = elative
* **+Err** = ?
* **+Fut** = future
* **+Fut1** = first future
* **+Gen** = genitive
* **+HabObj** = 
* **+HstPluPrf** = 
* **+HstPrf** = 
* **+IG** = gerund IG 
* **+Ill** = illative
* **+Imp** = imperative
* **+Ind** = indicative
* **+Ine** = inessive
* **+Inf** = infinitive
* **+Ins** = instrumental 
* **+Instr** = instrument (semantic tag)
* **+Interj** = interjection
* **+Interr** = interrogative
* **+KEZHLO** = gerund KEZHLO
* **+LEFT** = left edge (?)
* **+MOZ** = gerund MOZ 
* **+MYS** = gerund MYS 
* **+MYST** = gerund MYS
* **+N** = noun
* **+Neg** = negative
* **+Nom** = nominative
* **+Num** = numeral
* **+OM** = 
* **+Onom** = onomatopoetic
* **+Opt** = optative
* **+Ord** = ordinal
* **+PUNCT** = punctuation
* **+Pcle** = particle
* **+Pl** = plural
* **+Pl1** = 1st plural
* **+Pl2** = 2nd plural
* **+Pl3** = 3rd plural
* **+PluPrf** = pluperfect
* **+Po** = postposition
* **+Pos** = positive
* **+Prf** = perfective
* **+PrfIpf** = ?
* **+Prl** = prolative
* **+Pron** = pronoun
* **+Prop** = proprium (name)
* **+Prs** = present tense
* **+Prt1** = first past tense
* **+Prt2** = second past tense
* **+PxPl1** = 1st plural possessive suffix
* **+PxPl2** = 2nd plural possessive suffix
* **+PxPl3** = 3rd plural possessive suffix
* **+PxSg1** = 1st singular possessive suffix
* **+PxSg2** = 2nd singular possessive suffix
* **+PxSg3** = 3rd singular possessive suffix
* **+RIGHT** = right edge (?)
* **+Recipr** = reciprocal
* **+Refl** = reflexive
* **+Rel** = relative
* **+SOR** = ?
* **+Sg** = singular
* **+Sg1** = 1st singular
* **+Sg2** = 2nd singular
* **+Sg3** = 3rd singular
* **+Superl** = superlative
* **+TODZ** = gerund TODZ
* **+TYR** = gerund TYR
* **+TYRJI** = gerund TYR
* **+Temp** = ?
* **+Ter** = terminative
* **+Tra** = translative
* **+V** = verb
