# Лексикон проекта коми

Файлы для лексики Коми находятся здесь (Вы должны выбрать, возможно, "Показать исходный код!" в браузере):

* [A-SUPERL_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/A-SUPERL_kom-lex.xml)
* [ADVROOT_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/ADVROOT_kom-lex.xml)
* [ADV_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/ADV_kom-lex.xml)
* [A_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/A_kom-lex.xml)
* [CONJ_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/CONJ_kom-lex.xml)
* [IDIOM_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/IDIOM_kom-lex.xml)
* [INTERJ_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/INTERJ_kom-lex.xml)
* [NUM_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/NUM_kom-lex.xml)
* [N_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/N_kom-lex.xml)
* [NounOBJ.txt](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/NounOBJ.txt)
* [PART-ONOM_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PART-ONOM_kom-lex.xml)
* [PART_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PART_kom-lex.xml)
* [POSTP_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/POSTP_kom-lex.xml)
* [PRON-DEM_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-DEM_kom-lex.xml)
* [PRON-INDEF_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-INDEF_kom-lex.xml)
* [PRON-INTER_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-INTER_kom-lex.xml)
* [PRON-PERS_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-PERS_kom-lex.xml)
* [PRON-Q_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-Q_kom-lex.xml)
* [PRON-REFL_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON-REFL_kom-lex.xml)
* [PRON_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PRON_kom-lex.xml)
* [PROP_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/PROP_kom-lex.xml)
* [V-INST_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/V-INST_kom-lex.xml)
* [V-REFL_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/V-REFL_kom-lex.xml)
* [VNEG_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/VNEG_kom-lex.xml)
* [V_kom-lex.xml](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/V_kom-lex.xml)
* [examples.txt](https://gtsvn.uit.no/langtech/trunk/kt/kom/src/working_files/examples.txt)
